[colors.bright]
black = "0x4b5668"
blue = "0x5294e2"
cyan = "0x00aba5"
green = "0xa6e22e"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xd3dae3"
yellow = "0xe2b86b"

[colors.normal]
black = "0x2f343f"
blue = "0x5294e2"
cyan = "0x00aba5"
green = "0xa6e22e"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xd3dae3"
yellow = "0xe2b86b"

[colors.primary]
background = "0x2f343f"
foreground = "0xcdd6f4"

[cursor]
style = "Block"

[font]
size = 9

[font.bold]
family = "Monospace"
style = "Bold"

[font.italic]
family = "Monospace"
style = "Italic"

[font.normal]
family = "Monospace"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.80
dynamic_padding = true

[window.dimensions]
columns = 120
lines = 30

[window.padding]
x = 5
y = 5
